// import { Geist, Geist_Mono } from "next/font/google";
// import { StackProvider, StackTheme } from "@stackframe/stack";
// import { stackServerApp } from "../stack";
// import "./globals.css";
// import Provider from "./provider";
// import { Toaster } from "sonner";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       ><StackProvider app={stackServerApp}><StackTheme>
//         <Provider>
//           {children}
//           <Toaster />
//         </Provider>
//       </StackTheme></StackProvider></body>
//     </html>
//   );
// }
// "use client";

// import { Geist, Geist_Mono } from "next/font/google";
// import { ClerkProvider } from "@clerk/nextjs";
// import "./globals.css";
// import Provider from "./provider";
// import { Toaster } from "sonner";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body
//           className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//         >
//           <Provider>
//             {children}
//             <Toaster />
//           </Provider>
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }

// 'use client';

// import { Geist, Geist_Mono } from 'next/font/google';
// import { ClerkProvider } from '@clerk/nextjs';
// import './globals.css';
// import Provider from './provider';
// import { Toaster } from 'sonner';
// import ClientAuthProvider from './ClientAuthProvider';
// import { ConvexReactClient, ConvexProvider } from 'convex/react';

// // REMOVED: import { StackProvider } from '@stackframe/stack'; 
// // The error-causing library is gone.

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

// const convex = new ConvexReactClient(
//   process.env.NEXT_PUBLIC_CONVEX_URL || 'http://localhost:3000'
// );

// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider>
//       {/* REMOVED: <StackProvider> */}
//       <html lang="en">
//         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//           <ConvexProvider client={convex}>
//             <Provider>
//               <ClientAuthProvider>
//                 {children}
//               </ClientAuthProvider>
//               <Toaster />
//             </Provider>
//           </ConvexProvider>
//         </body>
//       </html>

//     </ClerkProvider>
//   );
// }


// 'use client';

// import { Inter, Space_Mono } from 'next/font/google';
// import { ClerkProvider } from '@clerk/nextjs';
// import './globals.css';
// import Provider from './provider'; // Assuming this provides UI context (e.g., Theme)
// import { Toaster } from 'sonner';
// import ClientAuthProvider from './ClientAuthProvider'; // Now strictly the Clerk/Convex linker
// // Removed unnecessary imports related to Convex client instantiation

// const sansFont = Inter({
//   variable: '--font-sans',
//   subsets: ['latin'],
// });

// const monoFont = Space_Mono({
//   weight: ['400', '700'],
//   variable: '--font-mono',
//   subsets: ['latin'],
// });

// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body className={`${sansFont.variable} ${monoFont.variable} antialiased`}>
//           {/* 1. Link Clerk and Convex Authentication first */}
//           <ClientAuthProvider>
//             {/* 2. Then, wrap with your custom providers (AuthProvider is now gone) */}
//             <Provider>
//               {children}
//             </Provider>
//             <Toaster />
//           </ClientAuthProvider>
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }

// app/layout.js

'use client';

import { Inter, Space_Mono } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import './globals.css';
import Provider from './provider'; // Assuming this provides UI context (e.g., Theme)
import { Toaster } from 'sonner';
import ClientAuthProvider from './ClientAuthProvider';
import UserSync from './UserSync'; // <-- 1. Import the new sync component

const sansFont = Inter({
  variable: '--font-sans',
  subsets: ['latin'],
});

const monoFont = Space_Mono({
  weight: ['400', '700'],
  variable: '--font-mono',
  subsets: ['latin'],
});

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${sansFont.variable} ${monoFont.variable} antialiased`}>
          {/* 1. Link Clerk and Convex Authentication first */}
          <ClientAuthProvider>

            <UserSync />


            <Provider>
              {children}
            </Provider>
            <Toaster />
          </ClientAuthProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}